services:
  # backend:
  #   image: backend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  db:
    ports: 
    - 5432:5432
    image: postgres
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=twitter

